name: dribbble_clone
description: Dribbble website clone using flutter

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter_html: ^0.11.0
  http: ^0.12.0+2
  flutter_masked_text: ^0.8.0
  dio: ^3.0.5
  shimmer: ^1.0.1
  connectivity: ^0.4.5+3
  shared_preferences: ^0.5.3+4
  json_annotation: ^2.0.0
  google_maps_flutter: ^0.5.11
  location: ^2.3.5
  intl: ^0.16.0
  flutter_staggered_grid_view: ^0.3.0
  cached_network_image: ^2.0.0-rc
  get_it: ^3.0.1
  mobx: ^0.3.8+1
  charts_flutter: ^0.8.1
  flutter_mobx: ^0.3.3
  url_launcher: ^5.2.7
  image_picker: ^0.6.2+1
  share: ^0.6.3+5
  division: ^0.8.7+2
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  mobx_codegen: ^0.3.9
  flutter_launcher_icons: "^0.7.3"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_plis.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-B.ttf
          weight: 700
        - asset: assets/fonts/Ubuntu-L.ttf
          weight: 300
        - asset: assets/fonts/Ubuntu-M.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu-R.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Thin.ttf
          weight: 100